### ISSUE TITLE
[Bug]: "V1 Backup" Problem on V2

### ISSUE THREAD

**Issue by BlaztOne** [chaldea-center/chaldea#50]
### What happened?

I tried to import my backup file from V1 to V2. In the last update, it worked perfectly fine.
I downloaded the new version to see if the QP calculation problem had been gone or not.
Then I discovered this new bug. It will happen if I try to import my V1 backups to V2.
Another thing to add, please explain to me the idea of the account thing. I "downloaded" the backup from the server and it just didn't do anything. The document is kinda confusing for me
Here's the proof of the bug:
[
![image](https://user-images.githubusercontent.com/69741876/164586335-6c289eb4-f6b8-4895-9081-8d366331a040.png)
](url)

### Platform

- [ ] web
- [ ] ios
- [ ] android
- [x] windows
- [ ] linux
- [ ] macOS

### Device Info

Windows 8.1

### Which game server is related to this issue?

JP

### App Version

V2 1.8.0(800) 6eb24a

### Relevant log output

```shell
type '_OneByteString' is not a subtype of type 'int' in type cast
chaldea.crash.log
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:180)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:184)
├ [2022-04-22 09:39:02.831][INFO] Unique ID: C49B5B11-9293-56C6-B7AD-1BE0E3F2C831
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:84)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:186)
├ [2022-04-22 09:39:02.831][INFO] Resolved app version: cc.narumi.chaldea 1.8.0+800 6eb24a - 4/20/2022
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:119)
├ [2022-04-22 09:39:12.791][DEBUG] fetch gamedata version: DataVersion(2022-04-21T13:57:28, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187)
│ #1   _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614)
│ #2   new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186)
│ #3   new UserData.fromLegacy (package:chaldea/models/userdata/userdata.dart:124)
│ #4   _OldVersionDataImportState._importFile (package:chaldea/app/modules/import_data/v1_backup.dart:148)
│ #5   <asynchronous suspension>
├ type '_OneByteString' is not a subtype of type 'int' in type cast
├ [2022-04-22 09:42:20.218][ERROR] import failed
└-----------------------------------------------------------------------------------------------------------------------
├ #0   new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187)
│ #1   _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614)
│ #2   new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186)
│ #3   new UserData.fromLegacy (package:chaldea/models/userdata/userdata.dart:124)
│ #4   _OldVersionDataImportState._importFile (package:chaldea/app/modules/import_data/v1_backup.dart:148)
│ #5   <asynchronous suspension>
├ type '_OneByteString' is not a subtype of type 'int' in type cast
├ [2022-04-22 09:42:27.456][ERROR] import failed
└-----------------------------------------------------------------------------------------------------------------------
├ #0   new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187)
│ #1   _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614)
│ #2   new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186)
│ #3   new UserData.fromLegacy (package:chaldea/models/userdata/userdata.dart:124)
│ #4   _OldVersionDataImportState._importFile (package:chaldea/app/modules/import_data/v1_backup.dart:148)
│ #5   <asynchronous suspension>
├ type '_OneByteString' is not a subtype of type 'int' in type cast
├ [2022-04-22 09:42:33.684][ERROR] import failed
└-----------------------------------------------------------------------------------------------------------------------
├ #0   new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187)
│ #1   _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614)
│ #2   new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186)
│ #3   new UserData.fromLegacy (package:chaldea/models/userdata/userdata.dart:124)
│ #4   _OldVersionDataImportState._importFile (package:chaldea/app/modules/import_data/v1_backup.dart:148)
│ #5   <asynchronous suspension>
├ type '_OneByteString' is not a subtype of type 'int' in type cast
├ [2022-04-22 09:42:44.200][ERROR] import failed
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:180)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:184)
├ [2022-04-22 09:48:31.921][INFO] Unique ID: C49B5B11-9293-56C6-B7AD-1BE0E3F2C831
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:84)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:186)
├ [2022-04-22 09:48:31.925][INFO] Resolved app version: cc.narumi.chaldea 1.8.0+800 6eb24a - 4/20/2022
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:119)
├ [2022-04-22 09:48:32.227][DEBUG] fetch gamedata version: DataVersion(2022-04-21T13:57:28, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:119)
├ [2022-04-22 09:48:57.188][DEBUG] fetch gamedata version: DataVersion(2022-04-21T13:57:28, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187)
│ #1   _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614)
│ #2   new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186)
│ #3   new UserData.fromLegacy (package:chaldea/models/userdata/userdata.dart:124)
│ #4   _OldVersionDataImportState._importFile (package:chaldea/app/modules/import_data/v1_backup.dart:148)
│ #5   <asynchronous suspension>
├ type '_OneByteString' is not a subtype of type 'int' in type cast
├ [2022-04-22 09:49:39.928][ERROR] import failed
└-----------------------------------------------------------------------------------------------------------------------
├ #0   new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187)
│ #1   _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614)
│ #2   new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186)
│ #3   new UserData.fromLegacy (package:chaldea/models/userdata/userdata.dart:124)
│ #4   new UserData.fromJson (package:chaldea/models/userdata/userdata.dart:72)
│ #5   _UserDataPageState.importUserData (package:chaldea/app/modules/home/subpage/user_data_page.dart:167)
│ #6   <asynchronous suspension>
├ type '_OneByteString' is not a subtype of type 'int' in type cast
├ [2022-04-22 09:50:30.733][ERROR] import user data failed
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:180)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:184)
├ [2022-04-22 09:51:01.442][INFO] Unique ID: C49B5B11-9293-56C6-B7AD-1BE0E3F2C831
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:84)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:186)
├ [2022-04-22 09:51:01.442][INFO] Resolved app version: cc.narumi.chaldea 1.8.0+800 6eb24a - 4/20/2022
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:119)
├ [2022-04-22 09:51:01.636][DEBUG] fetch gamedata version: DataVersion(2022-04-21T13:57:28, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:119)
├ [2022-04-22 09:51:24.888][DEBUG] fetch gamedata version: DataVersion(2022-04-21T13:57:28, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:180)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:184)
├ [2022-04-22 09:53:01.365][INFO] Unique ID: C49B5B11-9293-56C6-B7AD-1BE0E3F2C831
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:84)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:186)
├ [2022-04-22 09:53:01.380][INFO] Resolved app version: cc.narumi.chaldea 1.8.0+800 6eb24a - 4/20/2022
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:119)
├ [2022-04-22 09:53:01.648][DEBUG] fetch gamedata version: DataVersion(2022-04-21T13:57:28, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:119)
├ [2022-04-22 09:53:29.381][DEBUG] fetch gamedata version: DataVersion(2022-04-21T13:57:28, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187)
│ #1   _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614)
│ #2   new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186)
│ #3   new UserData.fromLegacy (package:chaldea/models/userdata/userdata.dart:124)
│ #4   _OldVersionDataImportState._importFile (package:chaldea/app/modules/import_data/v1_backup.dart:148)
│ #5   <asynchronous suspension>
├ type '_OneByteString' is not a subtype of type 'int' in type cast
├ [2022-04-22 09:55:27.405][ERROR] import failed
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:180)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:184)
├ [2022-04-23 15:01:55.224][INFO] Unique ID: C49B5B11-9293-56C6-B7AD-1BE0E3F2C831
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:84)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:186)
├ [2022-04-23 15:01:55.224][INFO] Resolved app version: cc.narumi.chaldea 1.8.0+800 6eb24a - 4/20/2022
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:119)
├ [2022-04-23 15:01:55.890][DEBUG] fetch gamedata version: DataVersion(2022-04-21T13:57:28, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:119)
├ [2022-04-23 15:02:30.782][DEBUG] fetch gamedata version: DataVersion(2022-04-22T14:04:18, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187)
│ #1   _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614)
│ #2   new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186)
│ #3   new UserData.fromLegacy (package:chaldea/models/userdata/userdata.dart:124)
│ #4   _OldVersionDataImportState._importFile (package:chaldea/app/modules/import_data/v1_backup.dart:148)
│ #5   <asynchronous suspension>
├ type '_OneByteString' is not a subtype of type 'int' in type cast
├ [2022-04-23 15:02:51.200][ERROR] import failed
└-----------------------------------------------------------------------------------------------------------------------

```

**Comment by narumishi** [comment]
Can you upload the full logs here or through feedback?

If you download backup from server, it will replace all game accounts. If nothing happened, isn't that the backup is the same as local? The **document** - which document/page?

**Comment by BlaztOne** [comment]
full logs? How do I check that? The only error message I got yesterday is the one I showed you

**Comment by narumishi** [comment]
If on windows, logs locate at "path/to/chaldea/userdata/logs/*.log"

**Comment by BlaztOne** [comment]
Updated. You shall be able to see the error log in "Relevant Log Output"

**Comment by BlaztOne** [comment]
chaldea.crash.log is on my second .log file, btw

**Comment by narumishi** [comment]
fixed.
