### ISSUE TITLE
[Bug]: Laplace - Td Level issues

### ISSUE THREAD

**Issue by SharpnelXu** [chaldea-center/chaldea#83]
### What happened?

In Laplace:
- Td Level can be set to zero.
- Event Reward Svts' default Td lv is not 5.

### Platform

All

### Which game server is related to this issue?

JP

### App Version

2.3.0+932

### Relevant log output

```shell
Error:
RangeError (index): Invalid value: Not in inclusive range 0..4: -1
Stack trace:
#0      _GrowableList.[] (dart:core-patch/growable_array.dart:264)
#1      BattleServantData.getNPGain (package:chaldea/app/battle/models/svt_entity.dart:322)
#2      BattleServantData.getCards (package:chaldea/app/battle/models/svt_entity.dart:262)
#3      _CombatActionSelectorState.build (package:chaldea/app/modules/battle/battle_simulation.dart:615)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968)
```

**Comment by SharpnelXu** [comment]
Fixed in #84
