### ISSUE TITLE
[Bug]: Segmentation Fault (Linux)

### ISSUE THREAD

**Issue by realmain** [chaldea-center/chaldea#89]
### What happened?

Had to install [`libayatana-appindicator`](https://archlinux.org/packages/community/x86_64/libayatana-appindicator/) for it to launch first per instructions or it wouldn't launch.

After that, when I try to launch the bin file, it pops up the blank GUI then closes itself.

Terminal:

```
flutter: ├ #0   PathManager.initRootPath (package:chaldea/models/paths.dart:119)
flutter: │ #1   _Database.initiate (package:chaldea/models/db.dart:134)
flutter: ├ [2023-05-13 17:22:21.758][INFO] appPath: /mnt/HynixSSD/Games/Chaldea/userdata
flutter: └---------
flutter: Linux machine id query:
6aeed864e74c47519665fdf0eee51708
flutter: ├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:162)
flutter: │ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:176)
flutter: ├ [2023-05-13 17:22:21.763][INFO] Unique ID: A41769AC-26C2-51D7-931F-9555C9D58005
flutter: └---------
flutter: ├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:88)
flutter: │ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:178)
flutter: ├ [2023-05-13 17:22:21.765][INFO] Resolved app version: chaldea 2.3.6+931 5daff7 - 5/11/2023
flutter: └---------
method call InitSystemTray
[1]    3422 segmentation fault (core dumped)  ./chaldea
```

### Platform

Linux

### Device Info

Arch Linux

### App Version

2.3.6

**Comment by realmain** [comment]
I actually already had `libappindicator-gtk3` installed for other programs, but it didn't work. I would get the error:

```
./chaldea: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
```

`libayatana-appindicator` is what provides `usr/lib/libayatana-appindicator3.so.1`, which fixes the above library error.

**Comment by realmain** [comment]
I'll test the new version once you release it to see if it is actually being caused by `InitSystemTray` and will let you know if that fixes the issue.

I was surprised that it didn't really provide much info to debug the issue in the terminal. Just Segmentation fault doesn't really explain much :/

**Comment by realmain** [comment]
The beta version works without any issues besides:

If I go in and toggle the system tray, the program crashes:

```
method call InitSystemTray
[1]    23712 segmentation fault (core dumped)  ./chaldea
```

When I go back into the program, it remains untoggled. So this must be a bug with the system tray. Well, at least I can use this for now!

**Comment by realmain** [comment]
Tested v2.3.6

**Ubuntu**
Worked out of the box. Worked.

**Zorin OS** (Ubuntu-based)
Had to install `libayatana-appindicator3`, `libayatana-ido3`, and then needed a newer glibc version (?) which I couldn't figure out on Zorin.

**OpenSUSE Tumbleweed**
Had to install `libayatana-appindicator3`, which automatically installed the other dependencies such as `libayatana-ido3`. Worked.

**Fedora**
Have to install `libayatana-appindicator3`, but I was unable to find the package. I don't know my way around Fedora.

**Comment by Hoithmach** [comment]
> Sorry to ping you @Hoithmach , what's your system distribution exactly? got confused last time. Is the latest version of this app still working on your machine? Thanks.

Very late to respond, sorry. I don't think GitHub notified me at all.

In case you're still looking for an answer:
I am also running Arch Linux on my main machine although I have access to several others, sorry to confuse you. I did experience a similar situation as described in this bug report with a previous version of Chaldea, however upgrading to the latest 2.4.4 release just now and installing `libayatana-appindicator` (on Arch Linux) appears to have resolved the issue.

I tested Ubuntu too - Works as expected after installing `libayatana-appindicator3-dev`. The only question I have is does it make sense to exchange the instructions for `libayatana-appindicator3-dev` (151MB of libraries) for `libayatana-appindicator3-1` (~400KB)? Both appear to work fine, but perhaps there is a reason I'm unaware of that the former is needed?

I'm happy to try look into the `glibc` problem as well, if you think it's still relevant?
